config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :admins
  devise_for :users
  resources :posts do 
    resources :coments
  end
  root 'posts#index'
  get 'welcome/index'
  get 'welcome/show'
  get 'welcome/admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coment.rb
class Coment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :coments, dependent: :destroy
    
 has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  has_many :posts
  has_many :coments

end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
 before_action :authenticate_admin!, only: [:action]

   protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache, :admin) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :password, :password_confirmation, :current_password, :avatar, :admin) }
    #devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name, address_attributes: [:country, :state, :city, :area]])
  end

  def authenticate_admin!
  authenticate_user!
  redirect_to :somewhere, status: :forbidden unless current_user.admin?
end

end

app/controllers/coments_controller.rb
class ComentsController < ApplicationController
  respond_to :html, :js, :json

  def create
    @post= Post.find(params[:post_id])
    @coment = @post.coments.create(comentario_params)
    #redirect_to post_path(@post
  end
 

  def destroy
    @post = Post.find(params[:post_id]) 
    @coment = @post.coments.find(params[:id])
    @coment.destroy
    #redirect_to post_path(@post), notice: 'coment was succesfully destroyed'

 

  end

  private
    def comentario_params
      params.require(:coment).permit(:comentarista, :contenido)
    end
end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, :authenticate_user!, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
     @post.user_id = current_user.id 
     @post.user_name = current_user.name 
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :coment }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:band, :album, :genere, :comments, :avatar, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def show
         @posts = Post.all
    end
     def admin
         @users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coments/_coment.html.erb
<div id='coment_<%= coment.id%>'>
 

 <p>
    <strong>Comentarista:</strong>
    <%= coment.comentarista %>
  </p>
 
  <p>
    <strong>Comentario:</strong>
    <%= coment.contenido %>
  </p>

<p>


  <%= link_to 'Borrar Comentario', [coment.post, coment],
               data: { confirm: "¿Estás #{coment.id}" }, 
               :remote => true,
               method: :delete %>
</p>
</div>

app/views/coments/_form.html.erb
<%= form_for([@post, @post.coments.build], remote: true, html: { :"data-type" => "json"}) do |f| %>
<div >
  <p>
    <%= f.label :comentarista %><br>
    <%= f.text_field :comentarista %>
  </p>
  <p>s
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %>
  </p>
  <p>
    <%= f.submit 'Guardar Comentario', class: 'create_coment' %>
  </p>
<% end %>
</div>

app/views/coments/create.js.erb
$('#list_coment').append('<div id="coment_<%= @coment.id %>">'+
 '<p>'+
    '<strong>Comentarista:</strong>'+
    '<%= @coment.comentarista %>'+
  '</p>'+
 
  '<p>'+
    '<strong>Comentario:</strong>'+
     '<%= @coment.contenido %>'+
  '</p>'+

'<p>'+
 ' <a data-confirm="¿Estás 161" class="delete_coment" data-remote="true" rel="nofollow" data-method="delete" href="/posts/<%= @post.id %>/coments/<%= @coment.id %>">Borrar Comentario</a>'+
'</p>'+
'</div>');

app/views/coments/destroy.js.erb
$('#list_coment').bind('ajax:success', function() {
    $('#coment_<%= @coment.id%>').fadeOut('slow');
    console.log('<%= @coment.id%>');
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tattopp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <li class="navbar-brand"><%= link_to 'Recomiendame un sitio', posts_path %></li>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to 'Acerca', welcome_index_path %></li>
     
      <li><%= link_to 'fotos', welcome_show_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">

<li> 
<%= if current_user.try(:admin?)
link_to "administrar cuentas", welcome_admin_path
end

%>
</li>
<% if current_user %>
      <li><%=current_user.name%> </li>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "editar perfil", edit_user_registration_path(current_user) %> </li>

     <li><div class=round-image-50 ><%= image_tag(current_user.avatar.url(:thumb)) %></div> </li>
  <% else %>
      <li><%= link_to 'Login', new_user_session_path %></li>

  <% end %>

    </ul>
  </div>
</nav>

    <%= yield %>
      <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :band, id: :post_band %>
  </div>

  <div class="field">
    <%= form.label :lugar %>
    <%= form.text_field :album, id: :post_album %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :genere, id: :post_genere %>
  </div>

  <div class="field">
    <%= form.label :commentarios %>
    <%= form.text_field :comments, id: :post_comments %>
  </div>
  <div class="field">
    <%= form.file_field :avatar %>
  </div>


  <% form.hidden_field :user_id %>
  <% form.hidden_field :user_name %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
        <div class="view hm-white-light jarallax" data-jarallax='{"speed": 0.2}' data-jarallax-video="https://youtu.be/QOZx5T1zDf0?list=RDGMEM6ijAnFTG9nX1G-kbWBUCJAVMQOZx5T1zDf0">
                <div class="container flex-center">
                            <div class="text-center text-muted">
                                <br>
                                <br>
                                <br>
                                <br>
                                <h3 class="display-2 mb-2 wow " > Lugares para parchar en medallo </h3>
                                <br>
                                <br>
                                <br>
                            </div>
                            <br>
                </div>
        </div>

<br>
<h4 class="text-center">Acá encontraras una serie de sitios recomendados por nuestros usuarios de la comunidad, la idea es no tener ningun tipo de influencia </h4>
<br>
<div class="text-center"> <h4><%= link_to 'New Post', new_post_path,:class => "text-center"  %> </h4></div>


<% @posts.each do |post| %>
               
<br>

                <div class="text-center">
              <td><%= image_tag post.avatar ,:class => 'division' %></td>
                        <div class="card-body secondbase">
                            <h4 class="card-title"><%= post.band %></h4>
                          <p class="card-text">Por: <a class="text-danger"><b><%= post.user_name%></b></a></p>
                             <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?',:remote => true,
                                     :method => :delete %></td>
                        
                    </div>
                </div>
 <% end %>

<hr>
<footer class="bg-dark text-white">
    <div class="text-center py-2 lead">Copyright © 2018 - David Rendon </div>
</footer>
    <script src="https://mdbootstrap.com/previews/docs/latest/js/jarallax.js"></script>
    <script src="https://mdbootstrap.com/previews/docs/latest/js/jarallax-video.js"></script>
    <script> 
        new WOW().init();
    </script>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>nombre:</strong>
  <%= @post.band %>
</p>

<p>
  <strong>lugar:</strong>
  <%= @post.album %>
</p>

<p>
  <strong>tipo:</strong>
  <%= @post.genere %>
</p>

<p>
  <strong>Comentarios:</strong>
  <%= @post.comments %>
</p>

<p>
  <strong></strong>
  <%= image_tag @post.avatar, style:'width:50px; height:150px'%>
</p>

<h2>Comentarios</h2>
<div id="list_coment">
  <%= render @post.coments %>
</div>


<h2>Añadir un comentario:</h2>
<%= render 'coments/form' %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/welcome/admin.html.erb
<table class="table">
  <thead>
    <tr class="info">
      
      <th>nombre</th>
      <th>nombre</th>
      <th>lugar</th>
      <th>tipo</th>
      <th>Comentarios</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>

      <tr>
        <td><%= image_tag user.avatar , style: 'height:20%; width:auto;' %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.updated_at %></td>
        <td><%= user.avatar %></td> 
        
    
  </div>
    <% end %>
  </tbody>

app/views/welcome/index.html.erb
<div class="text-center text-muted">


<% if current_user %>
      <h3 class="text-muted">Bienvenido <%= current_user.name %></h3>

      <h4 align="justify" > Este sitio fue creado para la gente que esta cansada de las recomendaciones de trip avisor y busca recomendaciones que se salgan de la influencia de precios o publicidades y solo se fije en la belleza de cada lugar como el disfrute cotidiano dejando atras la preocupación del dinero betches.</h4>

<br>

<%= image_tag("img.jpg",height: '325', width: '946')%>
<br>

<h4><%= link_to "ingresar a posts", posts_path %> </h4>

  <% else %>
  <h2> Ingrese porfavor </h2>
      <%= link_to 'Login', new_user_session_path %>
  <% end %>


<p>time<%= Time.now %></p>
</div>

app/views/welcome/show.html.erb
<h1>iMAGENES  </h1>

<% @posts.each do |post| %>

     
      

        <%= link_to (image_tag post.avatar), post %>
      <br>
    <% end %>